name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      # --- Checkout repo ---
      - uses: actions/checkout@v4

      # --- Setup Node ---
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # --- Install dependencies ---
      - name: Install dependencies
        run: npm ci

      # --- Install Playwright Browsers ---
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # --- CLEAN old Allure results (IMPORTANT) ---
      - name: Clean old Allure results
        run: rm -rf allure-results

      # --- Set unique run id ---
      - name: Set build id
        run: echo "ALLURE_RUN_ID=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      # --- Run Playwright tests ---
      - name: Run Playwright tests
        run: npx playwright test
        continue-on-error: true

      # --- Install Allure CLI ---
      - name: Install Allure CLI
        run: npm install -g allure-commandline

      # --- Generate Allure report ---
      - name: Generate Allure report
        run: allure generate allure-results --clean -o allure-report

      # --- FORCE content change (IMPORTANT) ---
      - name: Add build marker
        run: |
          echo "Run number: $GITHUB_RUN_NUMBER" > allure-report/build.txt
          echo "Commit: $GITHUB_SHA" >> allure-report/build.txt

      # --- Ensure allure-report exists ---
      - name: Ensure allure-report folder exists
        run: |
          if [ ! -d "allure-report" ]; then
            mkdir -p allure-report
            echo "No results" > allure-report/index.html
          fi

      # --- Deploy Allure report to GitHub Pages ---
      - name: Deploy Allure report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
          publish_branch: gh-pages
          allow_empty_commit: true

      # --- Upload Playwright HTML Report ---
      - name: Upload Playwright HTML report artifact
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
